website/auth.py
from flask import render_template, redirect, url_for, Blueprint, flash, request
from flask_login import login_required, login_user, logout_user, current_user
from website import db
from website.forms import (
    LoginForm,
    RegisterForm,
    ChangePasswordForm,
    ChangeUsernameForm,
    DeleteAccountForm,
    ResetPasswordForm,
)
from website.models import User
from website.utils.support import flash_errors, generate_token
from website.utils.emails_utils import send_password_reset_mail


auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["POST", "GET"])
def login_page():
    """
    Route for handling user login.

    If the current user is already authenticated, they are redirected to the home page.
    Otherwise, the login form is created and validated on submit.
    If the form is validated and the login credentials are correct, the user is logged in
    and redirected to the home page with a success flash message.
    If the form is not validated or the login credentials are incorrect, an error flash message is shown.

    Returns:
        The redirect response if the user is logged in, or the rendered login page response.
    """

    if current_user.is_authenticated:
        flash(message=f"You're already logged in!", category="info")
        return redirect(url_for("views.home_page"))

    login_form = LoginForm()

    if login_form.validate_on_submit():
        attempted_user = User.query.filter_by(email=login_form.email.data).first()
        if attempted_user and attempted_user.check_password_correction(
            attempted_password=login_form.password.data
        ):
            login_user(attempted_user)
            flash(message=f"Welcome back {attempted_user.username}", category="success")
            return redirect(url_for("views.home_page"))

        flash(
            message=f"Email and password don't match! Please try again.",
            category="danger",
        )
    return render_template("login-page.html", form=login_form)


@auth.route("register", methods=["POST", "GET"])
def register_page():
    """
    Register a new user.

    This route handles the registration process for a new user. It allows users to create an account by providing
    their desired username, email, and password. If the registration is successful, the user is redirected to the
    home page and a success message is displayed. If there are any validation errors with the registration form,
    corresponding error messages are flashed.

    Returns:
        If the registration is successful, redirects to the home page.
        If there are validation errors, renders the registration page with the corresponding error messages.

    """

    register_form = RegisterForm()

    if current_user.is_authenticated:
        flash(
            message=f"Log out first in order to create another account!",
            category="info",
        )
        return redirect(url_for("views.home_page"))

    if register_form.validate_on_submit():
        user_to_create = User(
            username=register_form.username.data,
            email=register_form.email.data,
        )
        user_to_create.password = register_form.password.data

        db.session.add(user_to_create)
        db.session.commit()
        flash(
            message=f"Account created successfully, welcome {user_to_create.username}!",
            category="info",
        )
        login_user(user_to_create)

        return redirect(url_for("views.home_page"))

    if register_form.errors != {}:
        flash_errors(register_form)

    return render_template("register-page.html", form=register_form)


@auth.route("/logout")
@login_required
def logout_page():
    """
    Log out the current user.

    This route logs out the current authenticated user. It calls the `logout_user` function provided by the Flask-Login
    extension to remove the user's session and clear the authentication state. After logging out, a flash message is
    displayed to inform the user, and they are redirected to the login page.

    Returns:
        A redirect response to the login page.

    """

    logout_user()
    flash(message=f"You have been logged out!", category="info")
    return redirect(url_for("auth.login_page"))


@auth.route("/settings", methods=["POST", "GET"])
@login_required
def settings_page():
    """
    Manage user settings.

    This route allows the user to manage their account settings. It provides forms for changing the username,
    changing the password, and deleting the account.

    If the change username form is submitted and valid, the user's username is updated to the new value and a success
    flash message is displayed. If the new username is the same as the current username, an info flash message is
    displayed.

    If the change password form is submitted and valid, the user's password is updated to the new value and a success
    flash message is displayed. If an error occurs during password update, a danger flash message is displayed.

    If the delete account form is submitted and valid, the user's account is deleted, they are logged out, and a success
    flash message is displayed.

    If there are validation errors in any of the forms, corresponding danger flash messages are displayed.

    Returns:
        A rendered template for the settings page.

    """

    change_username_form = ChangeUsernameForm()
    change_password_form = ChangePasswordForm()
    delete_account_form = DeleteAccountForm()

    if (
        change_username_form.validate_on_submit()
        and change_username_form.submit_username.data
    ):
        attempted_new_username = change_username_form.new_username.data

        if attempted_new_username == current_user.username:
            flash(message=f"This is already your username!", category="info")
        else:
            current_user.update_username(new_username=attempted_new_username)
            flash(
                message=f"You successfully changed your username to {current_user.username}",
                category="success",
            )

        return redirect(url_for("auth.settings_page"))

    elif (
        change_password_form.validate_on_submit()
        and change_password_form.submit_password.data
    ):
        try:
            current_user.update_password(
                old_password=change_password_form.old_password.data,
                new_password=change_password_form.new_password.data,
            )
            flash(message=f"Password has been changed", category="success")
        except ValueError:
            flash(message="Not successfull", category="danger")
        return redirect(url_for("auth.settings_page"))

    elif delete_account_form.validate_on_submit() and delete_account_form.submit.data:
        form_username = delete_account_form.username.data
        form_email = delete_account_form.email.data
        form_password = delete_account_form.password.data

        if form_username != current_user.username:
            flash(
                message=f"The username you entered doesn't match your account username!",
                category="danger",
            )
            return redirect(url_for("auth.settings_page"))

        if form_email != current_user.email:
            flash(
                message=f"The email you entered doesn't match your account email!",
                category="danger",
            )
            return redirect(url_for("auth.settings_page"))

        if not current_user.check_password_correction(form_password):
            flash(
                message=f"The password you entered doesn't match your account password!",
                category="danger",
            )
            return redirect(url_for("auth.settings_page"))

        username = current_user.username
        email = current_user.email
        logout_user()

        account_to_delete = User.query.filter_by(username=username, email=email).first()
        db.session.delete(account_to_delete)
        db.session.commit()
        flash(
            message=f"Your account has been deleted successfully!", category="success"
        )

        return redirect(url_for("auth.login_page"))

    if change_username_form.errors != {} and change_username_form.submit_username.data:
        flash_errors(change_username_form)

    if change_password_form.errors != {} and change_password_form.submit_password.data:
        flash_errors(change_password_form)

    if delete_account_form.errors != {} and delete_account_form.submit.data:
        flash_errors(delete_account_form)

    return render_template(
        "settings-page.html",
        password_form=change_password_form,
        username_form=change_username_form,
        delete_form=delete_account_form,
    )


@auth.route("/forgot-password", methods=["POST", "GET"])
@auth.route("/forgot-password/<email>", methods=["POST", "GET"])
def forgot_password_page(email: str = None):
    """
    Handle the forgot password functionality.

    This route is responsible for generating a password reset token for the user with the provided email address.
    It sends a password reset email to the user containing a unique reset link. If the user is found in the database,
    the reset token is assigned to the user's `reset_token` attribute and saved in the database. Then, the password
    reset email is sent to the user's email address.

    Parameters:
        email (str, optional): The email address of the user requesting a password reset.
            If not provided, the email will be retrieved from the form data.

    Returns:
        Redirect: Redirects the user to the settings page or login page.
    """

    if not email:
        email = request.form.get("email")

    user = User.query.filter_by(email=email).first()

    if user:
        token = generate_token()
        user.reset_token = token
        db.session.add(user)
        db.session.commit()

        reset_link = request.host_url + f"reset-password/{token}"

website/views.py
from flask import render_template, Blueprint, flash, request, redirect, url_for
from flask_login import login_required, current_user
from .utils.map_utils import extract_lat_long_via_address
from .utils.weather_utils import get_hourly_weather_data_single_day
from website.error_enums import ErrorEnum
from datetime import datetime
from website.forms import ContactForm
from website.utils.emails_utils import send_email_to_website


views = Blueprint("views", __name__)


@views.route("/", methods=["POST", "GET"])
@login_required
def home_page():
    """
    Renders the home page and handles the city and date form submission.

    If the request method is "POST":
    - Retrieves the submitted city and date from the request form.
    - If the city or date is empty, flashes an error message and redirects to the home page.
    - Redirects to the weather page for the specified city and date.

    Returns:
        If the request method is "POST", redirects to the weather page.
        If the request method is "GET", renders the "home-page.html" template.
    """

    if request.method == "POST":
        city = request.form.get("city")
        date = request.form.get("date")

        if city == "" or date == "":
            flash(message=f"Please enter a city and select a date!", category="danger")
            return redirect(url_for("views.home_page"))

        return redirect(
            url_for(
                "views.weather_page",
                city=city,
                date=date,
            )
        )

    return render_template("home-page.html")


@views.route("/contact", methods=["POST", "GET"])
@login_required
def contact_page():
    """
    Renders the contact page and handles the contact form submission.

    If the request method is "GET", initializes a new instance of the ContactForm.

    If the request method is "POST":
    - Validates the submitted contact form.
    - Sends an email to the website with the message from the contact form.
    - Flashes an informational message to confirm the message submission.
    - Redirects to the home page.

    Returns:
        If the request method is "GET", renders the "contact-page.html" template with the contact form.
        If the request method is "POST", redirects to the home page.
    """

    contact_form = ContactForm()

    if contact_form.validate_on_submit():
        send_email_to_website(contact_form.text_area.data)
        flash(
            message=f"We have received your message and we'll respond as fast as possible!",
            category="info",
        )

        return redirect(url_for("views.home_page"))

    return render_template("contact-page.html", form=contact_form)


@views.route("/weather/<city>/<date>")
@login_required
def weather_page(city: str, date: str):
    """
    Renders the weather page for a specific city and date.

    Args:
        city (str): The name of the city.
        date (str): The date in the format "YYYY-MM-DD".

    Returns:
        If successful, renders the "weather-page.html" template with the following parameters:
            - city: Titlecased city name.
            - date: Formatted date (month and year).
            - data_obj: Object containing hourly weather data for the specified city and date.
            - lat: Latitude of the city.
            - lng: Longitude of the city.
        If unsuccessful, flashes an error message and redirects to the home page.
    """

    lat_and_lng = extract_lat_long_via_address(city)

    if isinstance(lat_and_lng, ErrorEnum):
        flash(message=f"{lat_and_lng.value}", category="danger")
        return redirect(url_for("views.home_page"))

    data_obj = get_hourly_weather_data_single_day(city, date)

    if isinstance(data_obj, ErrorEnum):
        flash(message=f"{data_obj.value}", category="danger")
        return redirect(url_for("views.home_page"))

    date_ = datetime.strptime(date, "%Y-%m-%d")
    date = date_.strftime("%d %B %Y")
    current_user.update_history(city=city)

    return render_template(
        "weather-page.html",
        city=city.title(),
        date=date[:7],  # I don't want to display the year
        data_obj=data_obj,
        lat=lat_and_lng[0],
        lng=lat_and_lng[1],
    )


@views.route("/profile", methods=["POST", "GET"])
@login_required
def profile_page():
    """
    Renders the profile page and handles profile picture upload.

    If the request method is "POST", checks if a profile picture is included in the request files.
    If a profile picture is present, updates the current user's profile picture.
    Redirects to the profile page after processing the request.

    If the request method is "GET":
    - Validates the current user's profile picture.
    - Retrieves today's date and formats it.
    - Renders the "profile-page.html" template with the following parameters:
        - search_history: Reversed list of the current user's search history.
        - todays_date: Formatted string of today's date.
        - top_locations: List of the current user's top viewed cities.

    Returns:
        A rendered HTML template of the profile page.
    """

    if request.method == "POST":
        if "profile-pic" in request.files:
            file = request.files["profile-pic"]
            if file.filename != "":
                current_user.update_profile_pic(file)

        return redirect(url_for("views.profile_page"))

    current_user.validate_profile_pic()
    today_date = datetime.utcnow()
    today_date_formatted = datetime.strftime(today_date, "%Y-%m-%d")
    return render_template(
        "profile-page.html",
        search_history=current_user.search_history[::-1],
        # reverse the search history in order for the newest to be on top
        todays_date=today_date_formatted,
        top_locations=current_user.get_top_viewed_cities(),
    )

website/templates/base.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{ url_for('static', filename='styles/base.css')}}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    </head>

    <body>
        <div class="backdrop"></div>
        <title>
            {% block title %}
            
            {% endblock %}
        </title>

        
        <header class="main-header">
            <div>
                <button class="toggle-button">
                    <span class="toggle-button__bar"></span>
                    <span class="toggle-button__bar"></span>
                    <span class="toggle-button__bar"></span>
                </button>
            </div>

            <img src="{{ url_for('static', filename='images/icons/weather.png')}}" alt="weather-logo" class="main-nav-logo">
            <nav class="main-nav">
                <ul class="main-nav-links">
                    <li class="main-nav-link">
                        <a href="{{ url_for('views.home_page') }}">Home</a>
                    </li>

                    <li class="main-nav-link">
                        <a href="{{ url_for('views.contact_page') }}">Contact</a>
                    </li>
                    
                    {% if current_user.is_authenticated %}
                    <li class="main-nav-link">
                        <a href="{{ url_for('auth.logout_page') }}">Logout</a>
                    </li>

                    {% else %}
                        <li class="main-nav-link">
                            <a href="{{ url_for('auth.register_page') }}">Register</a>
                        </li>

                    {% endif %}
                </ul>
            </nav>
            
            {% if current_user.is_authenticated %}
                <a href="{{url_for('views.profile_page')}}">
                    <button class="main-nav-login-button">Profile</button>
                </a>
            {% else %}
                <a href="{{url_for('auth.login_page')}}" class="main-nav-login-link">
                    <button class="main-nav-login-button">Login</button>
                </a>
            {% endif %}
            

        </header>
        
        <div class="alert-container">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}" style="margin-bottom: 1rem;">
                    <button type="button" class="m1-2 mb-1 close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
 
    
        <nav class="mobile-nav">
            <ul class="mobile-nav-links">
                <li class="mobile-nav-link">
                    <a href="{{ url_for('views.home_page') }}">Home</a>
                </li>

                <li class="mobile-nav-link">
                    <a href="{{ url_for('views.contact_page') }}">Contact</a>
                </li>

                {% if current_user.is_authenticated %}
                    <li class="mobile-nav-link">
                        <a href="{{ url_for('auth.logout_page') }}">Logout</a>
                    </li>

                    <li class="mobile-nav-link">
                        <a href="{{ url_for('views.profile_page') }}">
                            <button class="mobile-nav-login-button">Profile</button>
                        </a>
                    </li>
                {% else %}

                    <li class="mobile-nav-link">
                        <a href="{{ url_for('auth.register_page') }}">Register</a>
                    </li>

                    <li class="mobile-nav-link">
                        <a href="{{ url_for('auth.login_page') }}">
                            <button class="mobile-nav-login-button">Login</button>
                        </a>
                    </li>

                {% endif %}
            </ul>
        </nav>

        

    


        {% block content %}

        {% endblock %}    


        <footer class="main-footer">
            <nav class="nav-footer">
                <ul class="nav-footer-links">
                    <li class="nav-footer-link">
                        <a class="nav-footer-link-1" href="#">About</a>
                    </li>

                    <li class="nav-footer-link">
                        <a class="nav-footer-link-2" href="#">Terms Of Use</a>
                    </li>
                </ul>
            </nav>
        </footer>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="{{ url_for('static', filename='js/mobile-nav.js')}}"></script>
        
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </body>
</html>

website/templates/contact-page.html
{% extends 'base.html' %}
{% block title %}
Contact
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/contact-page.css') }}">

<main>
    <div class="contact-form-container">
        <div class="contact-form-header">
            <h3>Questions?</h3>
            <h3>We're here to help.</h3>
        </div>

        <form action="{{ url_for('views.contact_page') }}" method="post">
            {{ form.hidden_tag() }}
            
            {{ form.text_area(rows=15, cols=80, class="text-area", placeholder="Type here") }}

            {{ form.submit(class="submit-btn") }}            
        </form>
    </div>

</main>


<script src="{{ url_for('static', filename='js/modals.js') }}"></script>
{% endblock %}

website/templates/home-page.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
<link rel="stylesheet" href="../static/styles/home-page.css">

<main>
    <div class="box">
        <div class="form-container">
            <h2>Enter a city and select a date</h2>

            <form action="{{ url_for('views.home_page')}}" method="post" name="weather-form" class="weather-form">
                <div class="city-container">
                    <label>City</label>
                    <input type="text" name="city" placeholder="City">
                </div>

                <div class="date-container">
                    <label>Date</label>
                    <input type="date" name="date">
                </div>

                <div class="submit-container">
                    <input type="submit" name="submit">
                </div>
            </form>
        </div>

        <div class="icons">
            <img src="//cdn.weatherapi.com/weather/64x64/day/113.png" alt="sunny" class="icon">
            <img src="//cdn.weatherapi.com/weather/64x64/day/116.png" alt="cloudy-sunny" class="icon">
            <img src="//cdn.weatherapi.com/weather/64x64/day/176.png" alt="sunny-rain" class="icon">
            <img src="//cdn.weatherapi.com/weather/64x64/day/308.png" alt="rain" class="icon">            
            <img src="//cdn.weatherapi.com/weather/64x64/day/230.png" alt="snow-wind" class="icon">
            <img src="//cdn.weatherapi.com/weather/64x64/day/338.png" alt="snow" class="icon">
            <img src="//cdn.weatherapi.com/weather/64x64/day/122.png" alt="cloudy" class="icon">
        </div>
    </div>
</main>

{% endblock %}

website/templates/login-page.html
{% extends 'base.html' %}

{% block title %}
Sign in
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/login-page.css' )}}">
<!-- desktop login -->
<div class="login-box">
    <div class="form-box login">
        <h2>Login</h2>
        <form action="{{ url_for('auth.login_page') }}" method="post" class="form-login">
            {{ form.hidden_tag() }}
            <div class="input-box">
                <span class="icon"><ion-icon name="mail"></ion-icon></span>
                {{ form.email(class="input-form")}}
                {{ form.email.label(class="label-form") }}
            </div>
            
            <div class="input-box">
                <span class="icon"><ion-icon name="lock-closed"></ion-icon></span>
                {{ form.password(class="input-form") }}
                {{ form.password.label(class="label-form")}}
            </div>

            <div class="remember-forgot">
                <label><input type="checkbox">Remember me</label>
                <a class="forgot-psw-link" href="#">Forgot Password?</a>
            </div>
            {{ form.submit(class="sign-in-button") }}

            <div class="login-register">
                <p>Don't have an account? <a href="{{ url_for('auth.register_page' )}}" class="register-link-desktop">Register</a></p>
            </div>
        </form>
    </div>
</div>


<!-- mobile login -->
<div class="header-container">
    <div class="headers">
        <h1 class="header-1">Let's sign you in.</h1>
        <h3 class="header-2">Welcome back.</h3>
        <h3 class="header-2">You've been missed!</h3>
    </div>
</div>


<div class="form-container">
    <form action="{{ url_for('auth.login_page') }}" method="post">
        <div class="mobile-forms">
            {{ form.hidden_tag() }}

            {{ form.email(class="form", placeholder="Username") }}

            {{ form.password(class="form", placeholder="Password") }}
        </div>
        <br>

        <div class="sign-in-container">
            <p class="account-text">Don't have an account? <a href="{{url_for('auth.register_page')}}" class="register-link">Register</a></p>
            {{ form.submit(class="submit-button") }}
        </div>
    </form>
</div>

<div class="forgot-psw-modal">
    <form action="{{ url_for('auth.forgot_password_page') }}" method="post" id="forgot-password-form">
        <label class="email-label" for="email">Enter the email associated with your account and we'll send you a link to reset your password.</label>
        <input class="email-field" type="email" name="email" id="email" placeholder="Email" required>
        <button class="email-submit" type="submit">Submit</button>
    </form>
</div>

<script src="{{ url_for('static', filename='js/modals.js') }}"></script>
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

{% endblock %}

website/templates/register-page.html
{% extends 'base.html' %}
{% block title %}
Register
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/register-page.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='styles/login-page.css' )}}">

<div class="register-box">
    <div class="form-box">
        <h2>Register</h2>
        <form action="{{ url_for('auth.register_page') }}" method="post" class="form-register">
            {{ form.hidden_tag() }}
            <div class="input-box">
                <span class="icon"><ion-icon name="person"></ion-icon></span>
                {{ form.username(class="input-form")}}
                {{ form.username.label(class="label-form")}}
            </div>

            <div class="input-box">
                <span class="icon"><ion-icon name="mail"></ion-icon></span>
                {{ form.email(class="input-form")}}
                {{ form.email.label(class="label-form")}}
            </div>

            <div class="input-box">
                <span class="icon"><ion-icon name="lock-closed"></ion-icon></span>
                {{ form.password(class="input-form")}}
                {{ form.password.label(class="label-form")}}
            </div>

            <div class="input-box">
                <span class="icon"><ion-icon name="lock-closed"></ion-icon></span>
                {{ form.retype_password(class="input-form")}}
                {{ form.retype_password.label(class="label-form")}}
            </div>

            {{ form.submit(class="sign-in-button") }}

            <div class="login-register">
            <p>Already have an account? <a href="{{ url_for('auth.login_page') }}" class="register-link-desktop">Sign In</a></p>
            </div>
        </form>
    </div>
</div>

<div class="header-container" style="margin-top: 4rem;">
    <h1 class="header-1">Hello!</h1>
    <h3 class="header-2">Sign up to get started!</h3>
</div>


<div class="form-container">
    <form action="{{ url_for('auth.register_page') }}" method="post">
        <div class="mobile-forms">
            {{ form.hidden_tag() }}

            {{ form.username(class="form", placeholder="Username")}}
            {{ form.email(class="form", placeholder="Email")}}
            {{ form.password(class="form", placeholder="Password") }}
            {{ form.retype_password(class="form", placeholder="Re-enter Password") }}
        </div>

        <br>
    
        <div class="sign-in-container">
            <p class="account-text">Already have an account? <a href="{{url_for('auth.login_page')}}" class="register-link">Sign In</a></p>
            {{ form.submit(class="submit-button") }}
        </div>
    </form>
</div>

<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
{% endblock %}

website/templates/reset-password-page.html
{% extends 'base.html' %}

{% block title %}
Reset Password
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/reset-password-page.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='styles/settings-page.css')}}">

<div class="reset-password-container">
    <div class="change-info-form">
        <h3>Enter a new password</h3>
        <form action="{{ url_for('auth.reset_password_page', token=token)}}" method="post">
            {{ form.hidden_tag() }}

            <div class="change-info-box-container">
                {{ form.new_password.label(class="change-label") }}
                {{ form.new_password(class="change-box") }}
            </div>

            <div class="change-info-box-container">
                {{ form.repeat_new_password.label(class="change-label") }}
                {{ form.repeat_new_password(class="change-box") }}

                {% if current_user.is_authenticated %}
                    <a class="return-to-website" href="{{ url_for('views.home_page') }}">Return to website!</a>
                {% else %}
                    <a class="return-to-website" href="{{ url_for('auth.login_page') }}"></a>
                {% endif %}
            </div>

            <div class="change-info-box-container">
                {{ form.submit(class="change-box-submit") }}
            </div>
        </form>
    </div>
</div>

{% endblock %}